sudo: required

services:
  - postgresql

language: python
python:
    - "3.6"

notifications:
  email: false

before_install:
  - export DB_NAME=meteo_service
  - export DB_USER=meteo_service
  - export DB_PASS=meteo_service
  - export DB_PORT=5432
  - export DB_HOST=localhost
  - psql -U postgres -c "CREATE USER $DB_USER PASSWORD '$DB_PASS'"
  - psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"
  - psql -U postgres -c "ALTER ROLE $DB_USER CREATEDB;"

install:
  - pip3 install -r requirements.txt
  - python3 manage.py migrate

script:
  - python3 manage.py test
