# Generated by Django 2.1.2 on 2018-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('forecast_datetime', models.DateTimeField(verbose_name='Forecast datetime')),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
